---
dist: bionic
language: python
python:
  - 3.7
sudo: required
services:
  - docker

jobs:
  include:
    - stage: full-test
      install:
        - pip install --upgrade pip
        - make dev-env
        - make lint-install
      script:
        - set -e
        - make docs
        - make lint-build-test-all DARGS="--build-arg TEST_ONLY_BUILD=1"

stages:
  - name: full-test
    if: type = cron AND branch = master