# Default to python3
- name: install python for ansible
  raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3-minimal)
  changed_when: False
- setup: # noqa 502

- name: install aptitude package with apt
  apt:
    name: aptitude
    force_apt_get: yes

- name: update all packages to the latest version
  apt:
    upgrade: "yes"
    update_cache: "yes"
    cache_valid_time: '3600'

- name: install required system packages # noqa 403
  apt:
    name:  "{{ item }}"
    state: latest
    update_cache: yes
  loop: [
    'apt-transport-https',
    'ca-certificates',
    'curl',
    'python3-pip',
    'python3-setuptools',
    'software-properties-common',
    'virtualenv'
  ]

- name: add docker gpg apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: update apt and install docker-ce # noqa 403
  apt:
    update_cache: yes
    name: docker-ce
    state: latest

- name: install docker python client
  pip:
    name: docker

- name: create a working directory
  file:
    path: "{{ working_dir }}"
    state: directory

- name: create workspaces working directories
  file:
    path: "{{ working_dir }}/workspaces/{{ item.dest }}"
    state: directory
  with_items:
    - dest: notebooks
    - dest: rstudio
    - dest: theia
    - dest: vscode
